Mydevelopment
tigerisbigcat/my-portfolio pull request #1
Opened 2022-06-08 18:42 UTC by tigerisbigcat

add some features to the home page.

2022-06-21 22:19 UTC, geegeex requested changes
Great job with the pull request! Left some comments. Please reach out if you have any questions!

2022-06-21 22:19 UTC, geegeex commented on portfolio/src/main/webapp/style.css
> +*/
It is best practice to not leave uncommented code in.

2022-06-21 22:19 UTC, geegeex commented on portfolio/src/main/webapp/style.css
> +/* menu settings */
Good job with the comments! It makes code more legible!

2022-06-21 22:19 UTC, geegeex commented on portfolio/src/main/webapp/script.js
> +    // // Now we can reference the fields in myObject!
Remove commented out code.

2022-06-21 22:19 UTC, geegeex commented on portfolio/src/main/webapp/script.js
> +    const textFromResponse = await responseFromServer.text() + "test";
Try to remove test fields from the response body ("test").

2022-06-21 22:19 UTC, geegeex commented on portfolio/src/main/webapp/index.html
> +            <!-- <div id="success">
Remove unused code.

2022-06-24 21:59 UTC, tigerisbigcat commented on portfolio/src/main/webapp/style.css
> +*/
test

2022-06-26 05:50 UTC, tigerisbigcat commented on portfolio/src/main/webapp/style.css
> +*/
I deleted it. Done.

2022-06-26 05:53 UTC, tigerisbigcat commented on portfolio/src/main/webapp/script.js
> +    // // Now we can reference the fields in myObject!
Done.

2022-06-26 05:54 UTC, tigerisbigcat commented on portfolio/src/main/webapp/script.js
> +    const textFromResponse = await responseFromServer.text() + "test";
Done.

2022-06-26 05:55 UTC, tigerisbigcat commented on portfolio/src/main/webapp/index.html
> +            <!-- <div id="success">
Done.

2022-06-29 00:33 UTC, geegeex approved these changes

2022-06-29 00:34 UTC, merged